name: Deploy

on:
  push:
    branches:
      - 'partial-fixes-deploy'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: '0'

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup just
        uses: extractions/setup-just@v2
        with:
          just-version: '1.25.2'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.5.6

      # TODO: add a build step here
      - name: deno deploy
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
        run: just deploy

